### ISSUE TITLE
Thunderbird CardDAV addressbook empty

### ISSUE THREAD

**Issue by kdato** [timsly/carddav#3]
I am on Thunderbird 73.3.1 (latest as of today). For it I installed TbSync + Provider for CalDAV & CardDAV.

The addons installed fine. My contacts are with mailo.com, their CardDAV URL + Port for Thunderbird is:
https://carddav.mailo.com/adbook/user.name@mailo.com/1:443

When configuring Provider for CalDAV & CardDAV, I chose manual config and entered the URL + Port exactly as shown (alongside my mailo username and password).

Provider for CalDAV & CardDAV synced fine, no messages or errors, and I get a green tick mark. The error log is empty.

Then, clicking on Thunderbird's "Address Book Button" shows the Mailo directory with the Provider for CalDAV & CardDAV icon. For that, I right-click and select "Default startup directory".

However, **the directory is empty, no contacts show.**

**Comment by timfjord** [comment]
Hi @kdato 
I am not sure there is the right repository to report this issue.
This repo holds a ruby implementation(ruby gem) of the CardDAV protocol and it has nothing to do with Thunderbird.
Maybe try reaching TbSync directly - https://github.com/jobisoft/TbSync

**Comment by kdato** [comment]
Thanks Tim, I'll report the issue on jbisoft/TbSync.
Best, kdato
